os: linux
dist: focal

language: python
python:
- "3.7"
- "3.8"
- "3.9"
- "3.10"
- "pypy3"

env:
- DEBIAN_DEPS=true
- DEBIAN_DEPS=

install:
- python -m pip install --upgrade pip setuptools wheel
- python -m pip --version
- python -m pip install --upgrade pytest pytest-asyncio pylint flake8
- if [   $DEBIAN_DEPS ]; then python -m pip install --upgrade protobuf==3.12.4; fi
- if [ ! $DEBIAN_DEPS ]; then python -m pip install --upgrade protobuf; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m pip install --upgrade mypy mypy-protobuf types-protobuf; fi
- python -m pip install .

script:
- export MYPYPATH=stubs/
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict twomemo/; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict tests/; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict setup.py; fi
- python -m pylint twomemo/
- python -m pylint tests/*.py
- python -m pylint setup.py
- python -m flake8 twomemo/
- python -m flake8 tests/*.py
- python -m flake8 setup.py
- python -m pytest
